apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-creds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: './'
    directory:
      include: 'manifest.yaml'
    repoURL: 'https://github.com/alexellis/registry-creds'
    targetRevision: master
  destination:
    namespace: registry-creds-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
